// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddCallLogEntry(arg1:string,arg2:string,arg3:string,arg4:number):Promise<void>;

export function AnswerCall():Promise<string>;

export function ClearAccount():Promise<void>;

export function ClearCallHistory():Promise<Array<main.CallLog>>;

export function DeleteContact(arg1:string):Promise<Array<main.Contact>>;

export function EmitEvent(arg1:string,arg2:any):Promise<void>;

export function GetAudioDevices():Promise<Record<string, any>>;

export function GetCallHistory():Promise<Array<main.CallLog>>;

export function GetContacts():Promise<Array<main.Contact>>;

export function HangupCall():Promise<string>;

export function LoadAccount():Promise<Record<string, any>>;

export function MakeCall(arg1:string):Promise<string>;

export function MuteMicrophone(arg1:boolean):Promise<void>;

export function RegisterSIP(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:boolean):Promise<string>;

export function RejectCall():Promise<string>;

export function SaveAccount(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string,arg7:string,arg8:boolean,arg9:boolean):Promise<string>;

export function SaveContact(arg1:string,arg2:string):Promise<Array<main.Contact>>;

export function SendDTMF(arg1:string):Promise<string>;

export function SetAudioDevices(arg1:string,arg2:string):Promise<void>;

export function UnregisterSIP():Promise<string>;
