// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddCallLogEntry(arg1, arg2, arg3, arg4) {
  return window['go']['main']['App']['AddCallLogEntry'](arg1, arg2, arg3, arg4);
}

export function AnswerCall() {
  return window['go']['main']['App']['AnswerCall']();
}

export function ClearAccount() {
  return window['go']['main']['App']['ClearAccount']();
}

export function ClearCallHistory() {
  return window['go']['main']['App']['ClearCallHistory']();
}

export function DeleteContact(arg1) {
  return window['go']['main']['App']['DeleteContact'](arg1);
}

export function EmitEvent(arg1, arg2) {
  return window['go']['main']['App']['EmitEvent'](arg1, arg2);
}

export function GetAudioDevices() {
  return window['go']['main']['App']['GetAudioDevices']();
}

export function GetCallHistory() {
  return window['go']['main']['App']['GetCallHistory']();
}

export function GetContacts() {
  return window['go']['main']['App']['GetContacts']();
}

export function HangupCall() {
  return window['go']['main']['App']['HangupCall']();
}

export function LoadAccount() {
  return window['go']['main']['App']['LoadAccount']();
}

export function MakeCall(arg1) {
  return window['go']['main']['App']['MakeCall'](arg1);
}

export function MuteMicrophone(arg1) {
  return window['go']['main']['App']['MuteMicrophone'](arg1);
}

export function RegisterSIP(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['RegisterSIP'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function RejectCall() {
  return window['go']['main']['App']['RejectCall']();
}

export function SaveAccount(arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9) {
  return window['go']['main']['App']['SaveAccount'](arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
}

export function SaveContact(arg1, arg2) {
  return window['go']['main']['App']['SaveContact'](arg1, arg2);
}

export function SendDTMF(arg1) {
  return window['go']['main']['App']['SendDTMF'](arg1);
}

export function SetAudioDevices(arg1, arg2) {
  return window['go']['main']['App']['SetAudioDevices'](arg1, arg2);
}

export function UnregisterSIP() {
  return window['go']['main']['App']['UnregisterSIP']();
}
